# Generated by Django 6.0.1 on 2026-01-23 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0022_parthistory'),
        ('knowledge', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='related_assets',
            field=models.ManyToManyField(blank=True, related_name='knowledge_articles', to='assets.asset'),
        ),
    ]
