# Generated by Django 6.0.1 on 2026-01-11 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_customuser_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='employee_status',
            field=models.CharField(choices=[('ACTIVE', 'Active'), ('PROBATION', 'Probation'), ('CONTRACT', 'Contract'), ('RESIGNED', 'Resigned')], default='ACTIVE', max_length=20),
        ),
        migrations.AddField(
            model_name='customuser',
            name='job_title',
            field=models.CharField(blank=True, help_text='Official Job Title, e.g., Senior Accountant', max_length=100),
        ),
        migrations.AddField(
            model_name='customuser',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='photo',
            field=models.ImageField(blank=True, upload_to='users/photos/'),
        ),
    ]
