# Generated by Django 6.0.1 on 2026-01-17 16:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0015_infrastructure_capacity_infrastructure_photo_and_more'),
        ('core', '0004_customuser_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employees', to='assets.department'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employees', to='assets.location'),
        ),
    ]
