# Generated by Django 6.0.1 on 2026-01-18 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_historicalcustomuser'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(default='ITMS Pro', max_length=100)),
                ('logo', models.ImageField(default='img/default_logo.png', upload_to='branding/')),
                ('favicon', models.ImageField(blank=True, null=True, upload_to='branding/')),
                ('login_background', models.ImageField(blank=True, null=True, upload_to='branding/')),
                ('maintenance_mode', models.BooleanField(default=False)),
            ],
        ),
    ]
