# Generated by Django 6.0.1 on 2026-02-01 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_personalnote'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesetting',
            name='asset_id_prefix',
            field=models.CharField(default='PMG', help_text='Prefix for auto-generated Asset IDs (e.g. PMG-0001)', max_length=10),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='company_address',
            field=models.TextField(blank=True, help_text='Full address for report headers'),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='company_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='company_name',
            field=models.CharField(default='PT. PMG - PROPERTY', help_text='Used in Reports', max_length=100),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='company_phone',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
