# Generated by Django 6.0.1 on 2026-02-03 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_sitesetting_asset_id_prefix_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesetting',
            name='activation_code',
            field=models.CharField(default='d41d8cd98f00b204e9800998ecf8427e', help_text='System License Hash', max_length=255),
        ),
    ]
