# Generated by Django 6.0.1 on 2026-01-12 14:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assets', '0006_assetloan'),
    ]

    operations = [
        migrations.CreateModel(
            name='ISPLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g., Biznet Dedicated', max_length=200)),
                ('cid_number', models.CharField(help_text='Customer ID / Circuit ID', max_length=100)),
                ('capacity_mbps', models.IntegerField(help_text='Bandwidth in Mbps')),
                ('ip_static_public', models.GenericIPAddressField(blank=True, null=True)),
                ('contract_start', models.DateField()),
                ('contract_end', models.DateField()),
                ('monthly_cost', models.DecimalField(decimal_places=2, max_digits=12)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive')], default='Active', max_length=20)),
                ('support_phone', models.CharField(blank=True, max_length=50)),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='isp_lines', to='assets.vendor')),
            ],
        ),
        migrations.CreateModel(
            name='NetworkNode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g., Core Switch Lt 2', max_length=200)),
                ('type', models.CharField(choices=[('Server', 'Server'), ('Router', 'Router'), ('Switch', 'Switch'), ('Firewall', 'Firewall'), ('Access_Point', 'Access Point'), ('CCTV', 'CCTV'), ('Printer', 'Printer'), ('Other', 'Other')], max_length=50)),
                ('status', models.CharField(choices=[('Online', 'Online'), ('Offline', 'Offline'), ('Maintenance', 'Maintenance')], default='Online', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('asset', models.OneToOneField(blank=True, help_text='Link to Asset Inventory if exists', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='network_node', to='assets.asset')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assets.location')),
            ],
        ),
    ]
