# Generated by Django 6.0.1 on 2026-01-12 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='networknode',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, help_text='Management IP for Ping Check', null=True),
        ),
        migrations.AddField(
            model_name='networknode',
            name='last_checked',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='networknode',
            name='status',
            field=models.CharField(choices=[('Online', 'Online'), ('Offline', 'Offline'), ('Maintenance', 'Maintenance')], default='Online', help_text='Updated automatically via Ping Check', max_length=20),
        ),
    ]
