# Generated by Django 6.0.1 on 2026-01-12 14:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0002_networknode_ip_address_networknode_last_checked_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subnet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g., Server Farm VLAN 10', max_length=200)),
                ('cidr', models.CharField(help_text='e.g., 192.168.10.0/24', max_length=50)),
                ('gateway', models.GenericIPAddressField(blank=True, null=True)),
                ('vlan_id', models.IntegerField(blank=True, null=True)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='IPAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.GenericIPAddressField()),
                ('status', models.CharField(choices=[('Available', 'Available'), ('Assigned', 'Assigned'), ('Reserved', 'Reserved'), ('DHCP', 'DHCP')], default='Available', max_length=20)),
                ('mac_address', models.CharField(blank=True, max_length=50)),
                ('description', models.CharField(blank=True, help_text='e.g., Reserved for New Printer', max_length=200)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('node', models.ForeignKey(blank=True, help_text='Linked Network Device', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ip_allocations', to='network.networknode')),
                ('subnet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ips', to='network.subnet')),
            ],
        ),
    ]
