# Generated by Django 6.0.1 on 2026-01-12 15:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0006_assetloan'),
        ('network', '0003_subnet_ipaddress'),
    ]

    operations = [
        migrations.AddField(
            model_name='ipaddress',
            name='asset',
            field=models.ForeignKey(blank=True, help_text='Linked General Asset (e.g. Laptop/PC)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ip_allocations', to='assets.asset'),
        ),
    ]
