# Generated by Django 6.0.1 on 2026-01-17 14:51

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0005_downtimeevent'),
    ]

    operations = [
        migrations.AddField(
            model_name='downtimeevent',
            name='description',
            field=models.TextField(blank=True, help_text='Detailed description of the incident'),
        ),
        migrations.AddField(
            model_name='downtimeevent',
            name='impact',
            field=models.CharField(choices=[('High', 'High (Site Down)'), ('Medium', 'Medium (Partial)'), ('Low', 'Low (Minor)')], default='Medium', max_length=20),
        ),
        migrations.AlterField(
            model_name='downtimeevent',
            name='start_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
