# Generated by Django 6.0.1 on 2026-01-17 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0006_downtimeevent_description_downtimeevent_impact_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='networknode',
            name='mac_address',
            field=models.CharField(blank=True, help_text='e.g., 00:1A:2B:3C:4D:5E', max_length=50),
        ),
        migrations.AlterField(
            model_name='networknode',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, help_text='Management IP (Required for Ping)', null=True),
        ),
        migrations.AlterField(
            model_name='networknode',
            name='status',
            field=models.CharField(choices=[('Online', 'Online'), ('Offline', 'Offline'), ('Maintenance', 'Maintenance'), ('Unknown', 'Unknown')], default='Unknown', help_text='Updated via Ping Tool', max_length=20),
        ),
    ]
