# Generated by Django 6.0.1 on 2026-01-17 17:43

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0016_historicalasset'),
        ('network', '0007_networknode_mac_address_alter_networknode_ip_address_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='ipaddress',
            name='status',
            field=models.CharField(choices=[('Active', 'Active'), ('Free', 'Free'), ('Reserved', 'Reserved'), ('DHCP', 'DHCP')], default='Free', max_length=20),
        ),
        migrations.CreateModel(
            name='HistoricalNetworkNode',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g., Core Switch Lt 2', max_length=200)),
                ('type', models.CharField(choices=[('Server', 'Server'), ('Router', 'Router'), ('Switch', 'Switch'), ('Firewall', 'Firewall'), ('Access_Point', 'Access Point'), ('CCTV', 'CCTV'), ('Printer', 'Printer'), ('Other', 'Other')], max_length=50)),
                ('ip_address', models.GenericIPAddressField(blank=True, help_text='Management IP (Required for Ping)', null=True)),
                ('mac_address', models.CharField(blank=True, help_text='e.g., 00:1A:2B:3C:4D:5E', max_length=50)),
                ('status', models.CharField(choices=[('Online', 'Online'), ('Offline', 'Offline'), ('Maintenance', 'Maintenance'), ('Unknown', 'Unknown')], default='Unknown', help_text='Updated via Ping Tool', max_length=20)),
                ('last_checked', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('asset', models.ForeignKey(blank=True, db_constraint=False, help_text='Link to Asset Inventory if exists', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='assets.asset')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('location', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='assets.location')),
            ],
            options={
                'verbose_name': 'historical network node',
                'verbose_name_plural': 'historical network nodes',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
