# Generated by Django 6.0.1 on 2026-01-17 17:49

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0016_historicalasset'),
        ('network', '0008_alter_ipaddress_status_historicalnetworknode'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalIPAddress',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('address', models.GenericIPAddressField()),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Free', 'Free'), ('Reserved', 'Reserved'), ('DHCP', 'DHCP')], default='Free', max_length=20)),
                ('mac_address', models.CharField(blank=True, max_length=50)),
                ('description', models.CharField(blank=True, help_text='e.g., Reserved for New Printer', max_length=200)),
                ('updated_at', models.DateTimeField(blank=True, editable=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('asset', models.ForeignKey(blank=True, db_constraint=False, help_text='Linked General Asset (e.g. Laptop/PC)', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='assets.asset')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('node', models.ForeignKey(blank=True, db_constraint=False, help_text='Linked Network Device', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='network.networknode')),
                ('subnet', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='network.subnet')),
            ],
            options={
                'verbose_name': 'historical ip address',
                'verbose_name_plural': 'historical ip addresss',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
