# Generated by Django 6.0.1 on 2026-01-23 07:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0009_historicalipaddress'),
    ]

    operations = [
        migrations.RunSQL(
            sql="ALTER TABLE network_historicalipaddress DROP COLUMN IF EXISTS anydesk_id;",
            reverse_sql="ALTER TABLE network_historicalipaddress ADD COLUMN anydesk_id varchar(50) DEFAULT '';"
        ),
        migrations.RunSQL(
            sql="ALTER TABLE network_historicalipaddress DROP COLUMN IF EXISTS hostname;",
            reverse_sql="ALTER TABLE network_historicalipaddress ADD COLUMN hostname varchar(255) DEFAULT '';"
        ),
        migrations.RunSQL(
            sql="ALTER TABLE network_historicalipaddress DROP COLUMN IF EXISTS remote_port;",
            reverse_sql="ALTER TABLE network_historicalipaddress ADD COLUMN remote_port integer DEFAULT NULL;"
        ),
        migrations.RunSQL(
            sql="ALTER TABLE network_historicalipaddress DROP COLUMN IF EXISTS remote_protocol;",
            reverse_sql="ALTER TABLE network_historicalipaddress ADD COLUMN remote_protocol varchar(20) DEFAULT '';"
        ),
    ]
