# Generated by Django 6.0.1 on 2026-01-25 23:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0031_infrastructure_latitude_infrastructure_longitude'),
        ('network', '0010_fix_historical_ip_schema'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalnetworknode',
            name='infrastructure',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='Rack/Tower location', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='assets.infrastructure'),
        ),
        migrations.AddField(
            model_name='networknode',
            name='infrastructure',
            field=models.ForeignKey(blank=True, help_text='Rack/Tower location', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='network_nodes', to='assets.infrastructure'),
        ),
    ]
