# Generated by Django 6.0.1 on 2026-01-26 11:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0031_infrastructure_latitude_infrastructure_longitude'),
        ('network', '0011_historicalnetworknode_infrastructure_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='downtimeevent',
            name='location',
            field=models.ForeignKey(blank=True, help_text='Affected Location', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='downtime_events', to='assets.location'),
        ),
    ]
