# Generated by Django 6.0.1 on 2026-01-26 14:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0031_infrastructure_latitude_infrastructure_longitude'),
        ('network', '0012_downtimeevent_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='subnet',
            name='location',
            field=models.ForeignKey(blank=True, help_text='Branch/Site owner of this subnet', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subnets', to='assets.location'),
        ),
    ]
