# Generated by Django 6.0.1 on 2026-01-26 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0013_subnet_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalipaddress',
            name='anydesk_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='ipaddress',
            name='anydesk_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
