# Generated by Django 6.0.1 on 2026-01-26 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0014_historicalipaddress_anydesk_id_ipaddress_anydesk_id'),
    ]

    operations = [

        migrations.AddField(
            model_name='ipaddress',
            name='hostname',
            field=models.CharField(default='unknown', max_length=255),
        ),
        migrations.AddField(
            model_name='ipaddress',
            name='remote_port',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ipaddress',
            name='remote_protocol',
            field=models.CharField(default='vnc', max_length=50),
        ),
    ]
