# Generated by Django 6.0.1 on 2026-01-26 15:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0015_historicalipaddress_hostname_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ipaddress',
            name='hostname',
        ),
        migrations.RemoveField(
            model_name='ipaddress',
            name='remote_port',
        ),
        migrations.RemoveField(
            model_name='ipaddress',
            name='remote_protocol',
        ),
    ]
