# Generated by Django 6.0.1 on 2026-01-28 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0016_remove_ipaddress_hostname_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='downtimeevent',
            name='notify_everyone',
            field=models.BooleanField(default=False, help_text='If checked, notifies ALL users in the location (including Staff). Default is IT Only.'),
        ),
    ]
