# Generated by Django 6.0.1 on 2026-01-11 15:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0002_asset'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssetIPAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField()),
                ('type', models.CharField(choices=[('LAN', 'LAN'), ('WAN', 'WAN'), ('VPN', 'VPN'), ('VLAN', 'VLAN')], default='LAN', max_length=10)),
                ('is_primary', models.BooleanField(default=False)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ip_addresses', to='assets.asset')),
            ],
        ),
        migrations.CreateModel(
            name='AssetSpecification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cpu', models.CharField(blank=True, max_length=100, null=True)),
                ('motherboard', models.CharField(blank=True, max_length=100, null=True)),
                ('ram', models.CharField(blank=True, max_length=100, null=True)),
                ('os', models.CharField(blank=True, max_length=100, null=True)),
                ('storage_devices', models.JSONField(blank=True, default=list)),
                ('asset', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='specification', to='assets.asset')),
            ],
        ),
        migrations.CreateModel(
            name='SoftwareAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('license_key', models.CharField(blank=True, max_length=200, null=True)),
                ('version', models.CharField(blank=True, max_length=50, null=True)),
                ('purchase_date', models.DateField(blank=True, null=True)),
                ('expiration_date', models.DateField(blank=True, null=True)),
                ('total_licenses', models.PositiveIntegerField(default=1)),
                ('vendor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='software_assets', to='assets.vendor')),
            ],
        ),
        migrations.CreateModel(
            name='SoftwareInstallation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('installed_date', models.DateField(blank=True, null=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='installed_software', to='assets.asset')),
                ('software', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='installations', to='assets.softwareasset')),
            ],
            options={
                'unique_together': {('software', 'asset')},
            },
        ),
    ]
