# Generated by Django 6.0.1 on 2026-01-11 15:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0003_assetipaddress_assetspecification_softwareasset_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CloudHosting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cloud_id', models.CharField(editable=False, max_length=50, unique=True)),
                ('service_name', models.CharField(max_length=200)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('renewal_type', models.CharField(choices=[('MONTHLY', 'Monthly'), ('YEARLY', 'Yearly'), ('ONE_TIME', 'One-Time'), ('PAY_AS_YOU_GO', 'Pay-As-You-Go')], default='MONTHLY', max_length=20)),
                ('monthly_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('EXPIRED', 'Expired'), ('SUSPENDED', 'Suspended'), ('CANCELLED', 'Cancelled')], default='ACTIVE', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('category', models.ForeignKey(limit_choices_to={'type__in': ['CL', 'SW']}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cloud_services', to='assets.category')),
                ('department', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cloud_services', to='assets.department')),
                ('provider', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cloud_services', to='assets.vendor')),
            ],
        ),
        migrations.CreateModel(
            name='Infrastructure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('infra_id', models.CharField(editable=False, max_length=50, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('install_date', models.DateField(blank=True, null=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='infra/photos/')),
                ('qr_code_image', models.ImageField(blank=True, null=True, upload_to='infra/qr/')),
                ('notes', models.TextField(blank=True)),
                ('location', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='infrastructure', to='assets.location')),
                ('vendor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='infrastructure', to='assets.vendor')),
            ],
        ),
    ]
