# Generated by Django 6.0.1 on 2026-01-11 15:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0004_cloudhosting_infrastructure'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='infrastructure',
            field=models.ForeignKey(blank=True, help_text='Linked infrastructure (e.g. Server Rack, Cabling)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assets', to='assets.infrastructure'),
        ),
    ]
