# Generated by Django 6.0.1 on 2026-01-12 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0006_assetloan'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='residual_value',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Estimated value at end of life', max_digits=12),
        ),
        migrations.AddField(
            model_name='asset',
            name='useful_life_years',
            field=models.IntegerField(default=5, help_text='Economic life in years'),
        ),
    ]
