# Generated by Django 6.0.1 on 2026-01-14 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0007_asset_residual_value_asset_useful_life_years'),
    ]

    operations = [
        migrations.AddField(
            model_name='assetspecification',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='assetspecification',
            name='mac_address',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
