# Generated by Django 6.0.1 on 2026-01-14 15:21

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0008_assetspecification_ip_address_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cloudhosting',
            old_name='service_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='softwareasset',
            old_name='expiration_date',
            new_name='expiry_date',
        ),
        migrations.RemoveField(
            model_name='assetipaddress',
            name='is_primary',
        ),
        migrations.RemoveField(
            model_name='assetloan',
            name='expected_return_date',
        ),
        migrations.RemoveField(
            model_name='assetloan',
            name='is_returned',
        ),
        migrations.RemoveField(
            model_name='cloudhosting',
            name='category',
        ),
        migrations.RemoveField(
            model_name='cloudhosting',
            name='department',
        ),
        migrations.RemoveField(
            model_name='cloudhosting',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='cloudhosting',
            name='notes',
        ),
        migrations.RemoveField(
            model_name='cloudhosting',
            name='renewal_type',
        ),
        migrations.RemoveField(
            model_name='cloudhosting',
            name='start_date',
        ),
        migrations.RemoveField(
            model_name='cloudhosting',
            name='status',
        ),
        migrations.RemoveField(
            model_name='infrastructure',
            name='install_date',
        ),
        migrations.RemoveField(
            model_name='infrastructure',
            name='photo',
        ),
        migrations.RemoveField(
            model_name='infrastructure',
            name='qr_code_image',
        ),
        migrations.RemoveField(
            model_name='infrastructure',
            name='vendor',
        ),
        migrations.RemoveField(
            model_name='softwareasset',
            name='total_licenses',
        ),
        migrations.RemoveField(
            model_name='softwareasset',
            name='vendor',
        ),
        migrations.AddField(
            model_name='cloudhosting',
            name='account_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='infrastructure',
            name='type',
            field=models.CharField(choices=[('RACK', 'Server Rack'), ('UPS', 'UPS / Power'), ('CABLING', 'Cabling'), ('COOLING', 'Cooling / AC'), ('OTHER', 'Other')], default='OTHER', max_length=20),
        ),
        migrations.AddField(
            model_name='softwareasset',
            name='license_type',
            field=models.CharField(choices=[('PERPETUAL', 'Perpetual'), ('SUBSCRIPTION', 'Subscription'), ('FREE', 'Free/Open Source')], default='PERPETUAL', max_length=20),
        ),
        migrations.AddField(
            model_name='softwareasset',
            name='seats',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='softwareasset',
            name='type',
            field=models.CharField(choices=[('OS', 'Operating System'), ('APP', 'Application'), ('DEV', 'Development Tool'), ('UTIL', 'Utility')], default='APP', max_length=10),
        ),
        migrations.AlterField(
            model_name='assetloan',
            name='condition_in',
            field=models.TextField(blank=True, help_text='Condition when returned', null=True),
        ),
        migrations.AlterField(
            model_name='assetloan',
            name='condition_out',
            field=models.TextField(blank=True, help_text='Condition when loaned', null=True),
        ),
        migrations.AlterField(
            model_name='cloudhosting',
            name='monthly_cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='cloudhosting',
            name='provider',
            field=models.CharField(choices=[('AWS', 'AWS'), ('GCP', 'Google Cloud'), ('AZURE', 'Azure'), ('DO', 'DigitalOcean'), ('OTHER', 'Other')], default='OTHER', max_length=20),
        ),
        migrations.AlterField(
            model_name='infrastructure',
            name='location',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='assets.location'),
        ),
        migrations.AlterField(
            model_name='infrastructure',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='softwareasset',
            name='license_key',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='softwareasset',
            name='version',
            field=models.CharField(default='0.0.0', max_length=50),
        ),
        migrations.AlterField(
            model_name='softwareinstallation',
            name='asset',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='software_installed', to='assets.asset'),
        ),
        migrations.AlterField(
            model_name='softwareinstallation',
            name='installed_date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.CreateModel(
            name='NetworkInterface',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g. eth0, WAN, Slot 1', max_length=50)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('mac_address', models.CharField(blank=True, max_length=50, null=True)),
                ('vlan_id', models.IntegerField(blank=True, help_text='VLAN Tag/ID', null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='network_interfaces', to='assets.asset')),
            ],
        ),
    ]
