# Generated by Django 6.0.1 on 2026-01-14 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0009_rename_service_name_cloudhosting_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
