# Generated by Django 6.0.1 on 2026-01-15 15:39

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0010_asset_notes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='softwareinstallation',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='softwareinstallation',
            name='software',
        ),
        migrations.RemoveField(
            model_name='softwareinstallation',
            name='asset',
        ),
        migrations.CreateModel(
            name='Software',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('license_key', models.CharField(blank=True, max_length=255, null=True)),
                ('license_type', models.CharField(choices=[('SUBSCRIPTION', 'Subscription'), ('PERPETUAL', 'Perpetual'), ('FREE', 'Free / Open Source'), ('TRIAL', 'Trial')], default='SUBSCRIPTION', max_length=20)),
                ('purchase_date', models.DateField(blank=True, null=True)),
                ('expiry_date', models.DateField(blank=True, help_text='Leave blank for Perpetual', null=True)),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('seats_total', models.PositiveIntegerField(default=1, help_text='Total number of licenses purchased')),
                ('seats_used', models.PositiveIntegerField(default=0, editable=False)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(blank=True, limit_choices_to={'type': 'SW'}, null=True, on_delete=django.db.models.deletion.SET_NULL, to='assets.category')),
                ('vendor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='assets.vendor')),
            ],
        ),
        migrations.CreateModel(
            name='SoftwareAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_date', models.DateField(default=django.utils.timezone.now)),
                ('notes', models.TextField(blank=True, null=True)),
                ('asset', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='software_installed', to='assets.asset')),
                ('employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='software_assets', to=settings.AUTH_USER_MODEL)),
                ('software', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allocations', to='assets.software')),
            ],
        ),
        migrations.DeleteModel(
            name='SoftwareAsset',
        ),
        migrations.DeleteModel(
            name='SoftwareInstallation',
        ),
    ]
