# Generated by Django 6.0.1 on 2026-01-15 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0011_remove_softwareinstallation_software_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CloudAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g. company.com or App Server', max_length=200)),
                ('provider', models.CharField(help_text='e.g. AWS, Niagahoster, GoDaddy', max_length=100)),
                ('service_type', models.CharField(choices=[('DOMAIN', 'Domain Name'), ('SHARED', 'Shared Hosting'), ('VPS', 'VPS / Cloud Server'), ('SSL', 'SSL Certificate'), ('SAAS', 'SaaS Subscription'), ('EMAIL', 'Email Hosting'), ('OTHER', 'Other')], default='DOMAIN', max_length=20)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('billing_cycle', models.CharField(choices=[('MONTHLY', 'Monthly'), ('YEARLY', 'Yearly'), ('ONETIME', 'One-time')], default='YEARLY', max_length=20)),
                ('cost', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('purchase_date', models.DateField(blank=True, null=True)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('auto_renew', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('PENDING', 'Pending'), ('SUSPENDED', 'Suspended'), ('EXPIRED', 'Expired'), ('CANCELLED', 'Cancelled')], default='ACTIVE', max_length=20)),
                ('login_url', models.URLField(blank=True, help_text='Login URL for management console', null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.DeleteModel(
            name='CloudHosting',
        ),
    ]
