# Generated by Django 6.0.1 on 2026-01-15 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0012_cloudasset_delete_cloudhosting'),
    ]

    operations = [
        migrations.AlterField(
            model_name='infrastructure',
            name='type',
            field=models.CharField(choices=[('RACK', 'Server Rack'), ('RACK_WALL', 'Rack Wallmount'), ('TOWER', 'Tower'), ('BOX_PANEL', 'Box Panel'), ('UPS', 'UPS / Power'), ('CABLING', 'Cabling'), ('COOLING', 'Cooling / AC'), ('OTHER', 'Other')], default='OTHER', max_length=20),
        ),
    ]
