# Generated by Django 6.0.1 on 2026-01-15 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0013_alter_infrastructure_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='infrastructure',
            name='condition',
            field=models.CharField(choices=[('EXCELLENT', 'Excellent'), ('GOOD', 'Good'), ('FAIR', 'Fair'), ('POOR', 'Poor'), ('CRITICAL', 'Critical')], default='GOOD', max_length=20),
        ),
        migrations.AddField(
            model_name='infrastructure',
            name='last_maintenance_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='infrastructure',
            name='next_maintenance_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
