# Generated by Django 6.0.1 on 2026-01-16 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0014_infrastructure_condition_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='infrastructure',
            name='capacity',
            field=models.CharField(blank=True, help_text='e.g. 42U, 1200VA', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='infrastructure',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='infrastructure/photos/'),
        ),
        migrations.AlterField(
            model_name='infrastructure',
            name='type',
            field=models.CharField(choices=[('TOWER', 'Tower'), ('SERVER_RACK', 'Server Rack'), ('WALLMOUNT', 'Rack Wallmount'), ('PANEL', 'Box Panel'), ('UPS', 'UPS / Power'), ('CABLING', 'Cabling'), ('COOLING', 'Cooling / AC'), ('OTHER', 'Other')], default='OTHER', max_length=20),
        ),
    ]
