# Generated by Django 6.0.1 on 2026-01-18 02:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0016_historicalasset'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='e.g. Microsoft 365 Renewal 2026', max_length=200)),
                ('contract_type', models.CharField(choices=[('LICENSE', 'Software License'), ('SERVICE', 'Service/Maintenance'), ('LEASE', 'Lease/Rental'), ('WARRANTY', 'Warranty Extension'), ('DOMAIN', 'Domain/Hosting'), ('ISP', 'ISP Contract'), ('OTHER', 'Other')], default='SERVICE', max_length=20)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('cost', models.DecimalField(decimal_places=2, help_text='Total Contract Value', max_digits=12)),
                ('document', models.FileField(blank=True, help_text='PDF/Docx Scan', null=True, upload_to='contracts/')),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('EXPIRED', 'Expired'), ('CANCELLED', 'Cancelled')], default='ACTIVE', editable=False, max_length=20)),
                ('notes', models.TextField(blank=True, null=True)),
                ('notify_days_before', models.IntegerField(default=30, help_text='Days before expiry to trigger alert')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contracts', to='assets.vendor')),
            ],
        ),
    ]
