# Generated by Django 6.0.1 on 2026-01-18 07:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0017_contract'),
        ('network', '0009_historicalipaddress'),
    ]

    operations = [
        migrations.AddField(
            model_name='networkinterface',
            name='subnet',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='network_interfaces', to='network.subnet'),
        ),
    ]
