# Generated by Django 6.0.1 on 2026-01-23 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0018_networkinterface_subnet'),
    ]

    operations = [
        migrations.AddField(
            model_name='assetloan',
            name='is_digital_sign',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='assetloan',
            name='signature_image',
            field=models.ImageField(blank=True, null=True, upload_to='signatures/'),
        ),
    ]
