# Generated by Django 6.0.1 on 2026-01-23 06:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0019_assetloan_is_digital_sign_assetloan_signature_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssetStorage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_type', models.CharField(choices=[('HDD', 'HDD'), ('SSD', 'SSD'), ('NVMe', 'NVMe'), ('RAM', 'RAM'), ('Other', 'Other')], default='HDD', max_length=10)),
                ('brand', models.CharField(blank=True, max_length=100, null=True)),
                ('capacity', models.CharField(help_text='e.g. 512GB, 1TB', max_length=50)),
                ('serial_number', models.CharField(blank=True, max_length=100, null=True)),
                ('purchase_date', models.DateField(blank=True, null=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='storages', to='assets.asset')),
            ],
            options={
                'verbose_name': 'Storage Device',
                'verbose_name_plural': 'Storage Devices',
                'db_table': 'assets_assetstorage',
            },
        ),
    ]
