# Generated by Django 6.0.1 on 2026-01-23 07:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0020_assetstorage'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.BigIntegerField(help_text='Legacy Audit Session ID')),
                ('status', models.CharField(max_length=20)),
                ('scanned_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.CharField(blank=True, max_length=255)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_items', to='assets.asset')),
            ],
            options={
                'verbose_name': 'Audit Record (Legacy)',
                'verbose_name_plural': 'Audit Records (Legacy)',
                'db_table': 'assets_audititem',
                'unique_together': {('session_id', 'asset')},
            },
        ),
    ]
