# Generated by Django 6.0.1 on 2026-01-23 07:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0021_audititem'),
    ]

    operations = [
        migrations.CreateModel(
            name='PartHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('part_name', models.CharField(max_length=100)),
                ('action_date', models.DateField()),
                ('description', models.TextField()),
                ('cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='part_history', to='assets.asset')),
                ('vendor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='assets.vendor')),
            ],
            options={
                'verbose_name': 'Part History (Legacy)',
                'verbose_name_plural': 'Part History (Legacy)',
                'db_table': 'assets_parthistory',
            },
        ),
    ]
