# Generated by Django 6.0.1 on 2026-01-23 08:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0022_parthistory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assetspecification',
            name='storage_devices',
        ),
    ]
