# Generated by Django 6.0.1 on 2026-01-23 11:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0023_remove_spec_storage_devices'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='parent',
            field=models.ForeignKey(blank=True, help_text='Parent location (e.g. Province for an RO)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='assets.location'),
        ),
        migrations.AddField(
            model_name='location',
            name='type',
            field=models.CharField(choices=[('HO', 'Head Office'), ('PROVINCE', 'Province'), ('RO', 'Regional Office'), ('ESTATE', 'Estate / Kebun'), ('MILL', 'Mill / PKS'), ('OTHER', 'Other')], default='OTHER', max_length=20),
        ),
    ]
