# Generated by Django 6.0.1 on 2026-01-24 09:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0026_department_manager'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DepartmentHead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='regional_heads', to='assets.department')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='regional_heads', to='assets.location')),
                ('manager', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='regional_roles', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Regional Head',
                'verbose_name_plural': 'Regional Heads',
                'unique_together': {('department', 'location')},
            },
        ),
    ]
