# Generated by Django 6.0.1 on 2026-01-25 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0027_departmenthead'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='auto_renew',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='contract',
            name='billing_cycle',
            field=models.CharField(choices=[('MONTHLY', 'Monthly'), ('YEARLY', 'Yearly'), ('ONE_TIME', 'One Time')], default='YEARLY', max_length=20),
        ),
        migrations.AddField(
            model_name='contract',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, help_text='For VPS/Hosting', null=True),
        ),
        migrations.AddField(
            model_name='contract',
            name='login_url',
            field=models.URLField(blank=True, help_text='Console/Dashboard URL', null=True),
        ),
        migrations.AlterField(
            model_name='contract',
            name='contract_type',
            field=models.CharField(choices=[('LICENSE', 'Software License'), ('SERVICE', 'Service/Maintenance'), ('LEASE', 'Lease/Rental'), ('WARRANTY', 'Warranty Extension'), ('DOMAIN', 'Domain Name'), ('HOSTING', 'Web Hosting / VPS'), ('SAAS', 'SaaS Subscription'), ('ISP', 'Internet Service Provider'), ('SSL', 'SSL Certificate'), ('OTHER', 'Other')], default='SERVICE', max_length=20),
        ),
    ]
