# Generated by Django 6.0.1 on 2026-01-25 09:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0028_contract_auto_renew_contract_billing_cycle_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='InfrastructureType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(editable=False, max_length=100, unique=True)),
                ('icon', models.CharField(choices=[('server', 'Server'), ('broadcast-tower', 'Tower'), ('hdd', 'Storage / Rack'), ('bolt', 'Power / Panel'), ('battery-full', 'UPS'), ('network-wired', 'Cabling'), ('snowflake', 'Cooling'), ('cube', 'Generic Cube'), ('wifi', 'Wireless'), ('video', 'Camera'), ('print', 'Printer')], default='cube', max_length=50)),
                ('color', models.CharField(choices=[('primary', 'Blue'), ('success', 'Green'), ('warning', 'Yellow'), ('danger', 'Red'), ('info', 'Cyan'), ('secondary', 'Gray')], default='primary', max_length=20)),
            ],
        ),
        migrations.AlterField(
            model_name='infrastructure',
            name='type',
            field=models.CharField(blank=True, choices=[('TOWER', 'Tower'), ('SERVER_RACK', 'Server Rack'), ('WALLMOUNT', 'Rack Wallmount'), ('PANEL', 'Box Panel'), ('UPS', 'UPS / Power'), ('CABLING', 'Cabling'), ('COOLING', 'Cooling / AC'), ('OTHER', 'Other')], default='OTHER', max_length=20),
        ),
        migrations.AddField(
            model_name='infrastructure',
            name='infra_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='items', to='assets.infrastructuretype'),
        ),
    ]
