# Generated by Django 6.0.1 on 2026-01-25 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0029_infrastructuretype_alter_infrastructure_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='infrastructuretype',
            name='is_featured',
            field=models.BooleanField(default=True, help_text='Show this type as a card on the dashboard'),
        ),
    ]
