# Generated by Django 6.0.1 on 2026-01-25 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0030_infrastructuretype_is_featured'),
    ]

    operations = [
        migrations.AddField(
            model_name='infrastructure',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='Lat coordinate, e.g. -6.200000', max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='infrastructure',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='Long coordinate, e.g. 106.816666', max_digits=9, null=True),
        ),
    ]
