# Generated by Django 5.2.13 on 2026-05-09 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0034_assetloan_is_permanent_alter_asset_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='sub_location',
            field=models.CharField(blank=True, help_text='e.g. Kantor PKS, Pabrik', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='historicalasset',
            name='sub_location',
            field=models.CharField(blank=True, help_text='e.g. Kantor PKS, Pabrik', max_length=100, null=True),
        ),
    ]
