# Generated by Django 5.2.13 on 2026-07-23 07:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0035_asset_sub_location_historicalasset_sub_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='previous_contract',
            field=models.OneToOneField(blank=True, help_text='The previous contract that this one renews/replaces', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='replaced_by', to='assets.contract'),
        ),
    ]
