# Generated by Django 5.2.13 on 2026-07-24 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0036_contract_previous_contract'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'Active'), ('EXPIRED', 'Expired'), ('CANCELLED', 'Cancelled'), ('PAID', 'Paid / Replaced')], default='ACTIVE', editable=False, max_length=20),
        ),
    ]
