# Generated by Django 5.2.13 on 2026-09-25 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0038_assetdocument'),
    ]

    operations = [
        migrations.AddField(
            model_name='infrastructure',
            name='manufacturing_date',
            field=models.DateField(blank=True, help_text='Tanggal dan Tahun Pembuatan', null=True, verbose_name='Manufacturing Date'),
        ),
    ]
