# Generated by Django 5.2.13 on 2026-09-25 07:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0039_infrastructure_manufacturing_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='InfraPartHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('part_name', models.CharField(max_length=100)),
                ('action_date', models.DateField()),
                ('description', models.TextField()),
                ('cost', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('infrastructure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='part_history', to='assets.infrastructure')),
                ('vendor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='assets.vendor')),
            ],
            options={
                'verbose_name': 'Infrastructure Part History',
                'verbose_name_plural': 'Infrastructure Part Histories',
                'ordering': ['-action_date'],
            },
        ),
    ]
