# Generated by Django 6.0.1 on 2026-01-24 10:25

import ckeditor.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assets', '0027_departmenthead'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, max_length=200, unique=True)),
                ('category', models.CharField(choices=[('TROUBLESHOOTING', 'Troubleshooting'), ('TUTORIAL', 'Tutorial / How-To'), ('SOP', 'SOP / Procedure'), ('GENERAL', 'General Info'), ('SCRIPT', 'Scripts & Configs')], default='GENERAL', max_length=50)),
                ('content', ckeditor.fields.RichTextField(help_text='Write your article here. Use Code Snippet for scripts.')),
                ('visibility', models.CharField(choices=[('PUBLIC', 'Public (All Staff)'), ('INTERNAL', 'Internal (IT Only)')], default='PUBLIC', max_length=20)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('PUBLISHED', 'Published'), ('ARCHIVED', 'Archived')], default='DRAFT', max_length=20)),
                ('views_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='articles', to=settings.AUTH_USER_MODEL)),
                ('related_assets', models.ManyToManyField(blank=True, help_text='Link to specific assets (e.g. Server X)', related_name='kb_articles', to='assets.asset')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
