"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.0.1.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""
import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get('SECRET_KEY', 'django-insecure-vm!@pmra2j3bz9o@dfl&05ip2bno7ba0(-si&#mwgg2g(a&8-t')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get('DEBUG', 'True') == 'True'

ALLOWED_HOSTS = os.environ.get('ALLOWED_HOSTS', '127.0.0.1,localhost').split(',')

# --- PRODUCTION SECURITY (Cloudflare/Nginx) ---
# Agar bisa login via HTTPS Cloudflare & Localhost
CSRF_TRUSTED_ORIGINS = os.environ.get('CSRF_TRUSTED_ORIGINS', 'https://itms.nubinote.my.id,http://localhost,http://127.0.0.1').split(',')

# Memberitahu Django bahwa request ini sebenarnya HTTPS (jika lewat proxy)
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')

# --- PRODUCTION SECURITY ---
if not DEBUG:
    # Cookies Stuffs
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    
    # HSTS (HTTP Strict Transport Security)
    # Memberitahu browser untuk selalu menggunakan HTTPS untuk jangka waktu tertentu
    SECURE_HSTS_SECONDS = 31536000  # 1 year
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True
    
    # Redirect HTTP to HTTPS (Jika tidak ditangani Nginx)
    SECURE_SSL_REDIRECT = True

# --- DEMO MODE ---
# Set to 'True' ONLY on demo servers. This blocks destructive actions (password reset, user delete, etc.)
DEMO_MODE = os.environ.get('DEMO_MODE', 'False') == 'True'


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.humanize',
    'core',
    'assets',
    'tickets',
    'maintenance',
    'governance',
    'import_export',
    'network',
    'knowledge',
    'notifications',
    'integrations',
    'knowledgebase',

    'ckeditor',

    'administration',
    'crispy_forms',
    'crispy_bootstrap5',
    'simple_history',
    'mptt',
]

CRISPY_ALLOWED_TEMPLATE_PACKS = "bootstrap5"
CRISPY_TEMPLATE_PACK = "bootstrap5"

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    "whitenoise.middleware.WhiteNoiseMiddleware",
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'administration.middleware.UserActivityMiddleware',
    'simple_history.middleware.HistoryRequestMiddleware',
    'core.middleware.LoginRequiredMiddleware',  # Global auth enforcement
    'core.middleware.MaintenanceMiddleware',
    'core.middleware.NavigationHistoryMiddleware',
    'core.middleware.RestrictAdminMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'assets.context_processors.notification_ctx',
                'core.context_processors.site_branding',
                'core.context_processors.license_processor', # License Info
                'maintenance.context_processors.maintenance_status',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': os.environ.get('POSTGRES_DB', 'dbitms2026'),
        'USER': os.environ.get('POSTGRES_USER', 'postgres'),      
        'PASSWORD': os.environ.get('POSTGRES_PASSWORD', 'delapan'),  
        'HOST': os.environ.get('POSTGRES_HOST', 'localhost'), # Default localhost for runserver, 'db' for Docker
        'PORT': os.environ.get('POSTGRES_PORT', '5432'),
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Asia/Jakarta'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = '/static/'
STATICFILES_DIRS = [BASE_DIR / 'static']
STATIC_ROOT = BASE_DIR / 'staticfiles'
STATICFILES_STORAGE = "whitenoise.storage.CompressedManifestStaticFilesStorage"

# Media files
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Custom User Model
AUTH_USER_MODEL = 'core.CustomUser'

# Auth settings
LOGIN_URL = 'login'
LOGIN_REDIRECT_URL = 'staff_dashboard'  # Default fallback
LOGOUT_REDIRECT_URL = 'login'

# Session Management
SESSION_COOKIE_AGE = 7200  # 2 Hours (7200 seconds)
SESSION_EXPIRE_AT_BROWSER_CLOSE = True
SESSION_SAVE_EVERY_REQUEST = True

# CKEditor Settings
CKEDITOR_CONFIGS = {
    'default': {
        'toolbar': 'Custom',
        'height': 400,
        'width': '100%',
        'extraPlugins': 'codesnippet',
        'toolbar_Custom': [
            ['Styles', 'Format', 'Bold', 'Italic', 'Underline', 'Strike', 'SpellChecker', 'Undo', 'Redo'],
            ['Link', 'Unlink', 'Anchor'],
            ['Image', 'Table', 'HorizontalRule', 'Blockquote'],
            ['TextColor', 'BGColor'],
            ['Smiley', 'SpecialChar'], 
            ['Source'],
            ['CodeSnippet'], 
            ['Maximize']
        ],
    },
}
