# Generated by Django 5.2.13 on 2026-05-04 04:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AIConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base_url', models.URLField(default='http://192.168.0.14:8080/v1', help_text='Base URL for the OpenAI compatible API (e.g., http://192.168.0.14:8080/v1)')),
                ('api_key', models.CharField(blank=True, help_text='API Key (Leave blank if not required by local AI, e.g. LM Studio or Ollama)', max_length=255)),
                ('model_name', models.CharField(default='local-model', help_text='Model name to use (often ignored by local models, but required by API format)', max_length=100)),
                ('system_prompt', models.TextField(default='You are a helpful IT Support Assistant for the ITMS Pro system. Keep your answers clear, technical but easy to understand, and polite.', help_text="Instructions to define the assistant's behavior and personality.")),
                ('is_active', models.BooleanField(default=True, help_text='Only the active configuration will be used.')),
            ],
            options={
                'verbose_name': 'AI Configuration',
                'verbose_name_plural': 'AI Configurations',
            },
        ),
        migrations.CreateModel(
            name='ChatSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_chat_sessions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('system', 'System'), ('user', 'User'), ('assistant', 'Assistant')], max_length=20)),
                ('content', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='ai_assistant.chatsession')),
            ],
            options={
                'ordering': ['timestamp'],
            },
        ),
    ]
