# Generated by Django 5.2.13 on 2026-05-04 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_assistant', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AIDataSkill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g., Check Old Assets', max_length=100)),
                ('description', models.TextField(blank=True, help_text='Describe what this skill does.')),
                ('trigger_keywords', models.TextField(help_text="Comma-separated keywords to trigger this query (e.g., 'aset lama, diatas 5 tahun').")),
                ('sql_query', models.TextField(help_text='Read-Only SQL Query (e.g., SELECT name, status FROM assets_asset WHERE ...). DO NOT use DELETE/UPDATE.')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'AI Data Skill',
                'verbose_name_plural': 'AI Data Skills',
            },
        ),
    ]
