# Generated by Django 6.0.1 on 2026-01-11 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('governance', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MonthlyReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_date', models.DateField(help_text='Select the 1st of the month')),
                ('generated_at', models.DateTimeField(auto_now=True)),
                ('total_tickets', models.IntegerField(default=0)),
                ('resolved_tickets', models.IntegerField(default=0)),
                ('avg_resolution_hours', models.FloatField(default=0.0)),
                ('sla_compliance_rate', models.FloatField(default=0.0, help_text='Percentage 0-100')),
                ('top_technician', models.CharField(blank=True, max_length=200)),
                ('most_common_issue', models.CharField(blank=True, max_length=200)),
                ('notes', models.TextField(blank=True, help_text="Manager's analysis")),
            ],
        ),
    ]
