# Generated by Django 6.0.1 on 2026-01-16 03:18

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('governance', '0002_monthlyreport'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projecttask',
            name='assigned_to',
        ),
        migrations.RemoveField(
            model_name='projecttask',
            name='project',
        ),
        migrations.AlterModelOptions(
            name='dailylog',
            options={'ordering': ['-date', '-created_at']},
        ),
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['-end_date']},
        ),
        migrations.RemoveField(
            model_name='dailylog',
            name='executor',
        ),
        migrations.RemoveField(
            model_name='dailylog',
            name='shift',
        ),
        migrations.AddField(
            model_name='dailylog',
            name='activity',
            field=models.CharField(default='Activity', help_text='Short summary of activity', max_length=200),
        ),
        migrations.AddField(
            model_name='dailylog',
            name='category',
            field=models.CharField(choices=[('SUPPORT', 'IT Support'), ('DEV', 'Development'), ('MAINTENANCE', 'Maintenance'), ('MEETING', 'Meeting'), ('INFRA', 'Infrastructure Check'), ('OTHER', 'Other')], default='SUPPORT', max_length=20),
        ),
        migrations.AddField(
            model_name='dailylog',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='dailylog',
            name='description',
            field=models.TextField(blank=True, help_text='Detailed outcome or notes', null=True),
        ),
        migrations.AddField(
            model_name='dailylog',
            name='duration',
            field=models.DecimalField(decimal_places=1, default=0.0, help_text='Duration in Hours (e.g. 1.5)', max_digits=4),
        ),
        migrations.AddField(
            model_name='dailylog',
            name='status',
            field=models.CharField(choices=[('COMPLETED', 'Completed'), ('PENDING', 'Pending')], default='COMPLETED', max_length=20),
        ),
        migrations.AddField(
            model_name='dailylog',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='daily_logs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='project',
            name='budget',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='priority',
            field=models.CharField(choices=[('HIGH', 'High'), ('MEDIUM', 'Medium'), ('LOW', 'Low')], default='MEDIUM', max_length=10),
        ),
        migrations.AddField(
            model_name='project',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='dailylog',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='project',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='project',
            name='end_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='project',
            name='progress',
            field=models.IntegerField(default=0, help_text='0-100%'),
        ),
        migrations.AlterField(
            model_name='project',
            name='start_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('PLANNING', 'Planning'), ('IN_PROGRESS', 'In Progress'), ('ON_HOLD', 'On Hold'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='PLANNING', max_length=20),
        ),
        migrations.DeleteModel(
            name='DailyLogItem',
        ),
        migrations.DeleteModel(
            name='RoutineTask',
        ),
        migrations.DeleteModel(
            name='ProjectTask',
        ),
    ]
