# Generated by Django 6.0.1 on 2026-01-16 03:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0015_infrastructure_capacity_infrastructure_photo_and_more'),
        ('governance', '0003_remove_projecttask_assigned_to_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoutineTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Standard Task Name (e.g. Daily Backup)', max_length=200)),
                ('category', models.CharField(choices=[('SUPPORT', 'IT Support'), ('DEV', 'Development'), ('MAINTENANCE', 'Maintenance'), ('MEETING', 'Meeting'), ('INFRA', 'Infrastructure Check'), ('OTHER', 'Other')], default='SUPPORT', max_length=20)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.AddField(
            model_name='dailylog',
            name='asset',
            field=models.ForeignKey(blank=True, help_text='Related Asset (optional)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='governance_logs', to='assets.asset'),
        ),
        migrations.AddField(
            model_name='dailylog',
            name='task',
            field=models.ForeignKey(blank=True, help_text='Select standard task or leave blank for custom', null=True, on_delete=django.db.models.deletion.SET_NULL, to='governance.routinetask'),
        ),
    ]
