# Generated by Django 6.0.1 on 2026-01-16 04:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('governance', '0004_routinetask_dailylog_asset_dailylog_task'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dailylog',
            options={},
        ),
        migrations.AlterModelOptions(
            name='project',
            options={},
        ),
        migrations.RemoveField(
            model_name='dailylog',
            name='activity',
        ),
        migrations.RemoveField(
            model_name='dailylog',
            name='asset',
        ),
        migrations.RemoveField(
            model_name='dailylog',
            name='category',
        ),
        migrations.RemoveField(
            model_name='dailylog',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='dailylog',
            name='description',
        ),
        migrations.RemoveField(
            model_name='dailylog',
            name='duration',
        ),
        migrations.RemoveField(
            model_name='dailylog',
            name='task',
        ),
        migrations.RemoveField(
            model_name='dailylog',
            name='user',
        ),
        migrations.RemoveField(
            model_name='project',
            name='budget',
        ),
        migrations.RemoveField(
            model_name='project',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='project',
            name='priority',
        ),
        migrations.RemoveField(
            model_name='project',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='routinetask',
            name='description',
        ),
        migrations.AddField(
            model_name='dailylog',
            name='executor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='dailylog',
            name='shift',
            field=models.CharField(default='Morning', max_length=50),
        ),
        migrations.AddField(
            model_name='routinetask',
            name='frequency',
            field=models.CharField(default='Daily', help_text='Daily, Weekly, Monthly', max_length=50),
        ),
        migrations.AlterField(
            model_name='dailylog',
            name='status',
            field=models.CharField(choices=[('Draft', 'Draft'), ('Submitted', 'Submitted'), ('Approved', 'Approved')], default='Draft', max_length=20),
        ),
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('Planning', 'Planning'), ('In Progress', 'In Progress'), ('On Hold', 'On Hold'), ('Completed', 'Completed'), ('Cancelled', 'Cancelled')], default='Planning', max_length=20),
        ),
        migrations.AlterField(
            model_name='routinetask',
            name='category',
            field=models.CharField(choices=[('Network', 'Network'), ('Server', 'Server'), ('Support', 'Support'), ('Development', 'Development')], max_length=50),
        ),
        migrations.AlterField(
            model_name='routinetask',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.CreateModel(
            name='DailyLogItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.TimeField(blank=True, null=True)),
                ('end_time', models.TimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('OK', 'OK'), ('Issue', 'Issue Found'), ('Fixed', 'Fixed')], default='OK', max_length=20)),
                ('note', models.TextField(blank=True)),
                ('log', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='governance.dailylog')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='governance.routinetask')),
            ],
        ),
        migrations.CreateModel(
            name='ProjectTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('is_completed', models.BooleanField(default=False)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='governance.project')),
            ],
        ),
    ]
