# Generated by Django 6.0.1 on 2026-01-16 04:19

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('governance', '0005_alter_dailylog_options_alter_project_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='dailylog',
            unique_together={('executor', 'date')},
        ),
    ]
