# Generated by Django 6.0.1 on 2026-01-16 16:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0015_infrastructure_capacity_infrastructure_photo_and_more'),
        ('governance', '0007_dailylogitem_content_type_dailylogitem_object_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailylog',
            name='note',
            field=models.TextField(blank=True, help_text='General summary of the day'),
        ),
        migrations.AddField(
            model_name='dailylogitem',
            name='category',
            field=models.CharField(choices=[('Network', 'Network'), ('Server', 'Server'), ('Support', 'Support'), ('Development', 'Development'), ('Meeting', 'Meeting'), ('Other', 'Other')], default='Other', max_length=50),
        ),
        migrations.AddField(
            model_name='dailylogitem',
            name='related_asset',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='daily_log_items', to='assets.asset'),
        ),
        migrations.AddField(
            model_name='dailylogitem',
            name='related_infra',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='daily_log_items', to='assets.infrastructure'),
        ),
        migrations.AddField(
            model_name='dailylogitem',
            name='task_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='dailylogitem',
            name='status',
            field=models.CharField(choices=[('Before', 'Before'), ('Completed', 'Completed'), ('In Progress', 'In Progress')], default='Completed', max_length=20),
        ),
    ]
