# Generated by Django 6.0.1 on 2026-01-16 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('governance', '0008_dailylog_note_dailylogitem_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailylog',
            name='shift',
            field=models.CharField(choices=[('Morning', 'Morning'), ('Afternoon', 'Afternoon'), ('Night', 'Night'), ('Full Day', 'Full Day')], default='Morning', max_length=50),
        ),
    ]
