# Generated by Django 6.0.1 on 2026-01-17 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('governance', '0009_alter_dailylog_shift'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailylog',
            name='work_location',
            field=models.CharField(choices=[('HO', 'Head Office'), ('SITE', 'On-Site / Visit'), ('REMOTE', 'Remote / WFH')], default='HO', max_length=10),
        ),
    ]
