# Generated by Django 6.0.1 on 2026-01-17 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('governance', '0010_dailylog_work_location'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projecttask',
            name='is_completed',
        ),
        migrations.AddField(
            model_name='projecttask',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='projecttask',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='projecttask',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('In Progress', 'In Progress'), ('Completed', 'Completed')], default='Pending', max_length=20),
        ),
    ]
