# Generated by Django 6.0.1 on 2026-01-17 09:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0015_infrastructure_capacity_infrastructure_photo_and_more'),
        ('governance', '0011_remove_projecttask_is_completed_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='budgetpost',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='assets.department'),
        ),
        migrations.AddField(
            model_name='budgetpost',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='assets.location'),
        ),
    ]
