# Generated by Django 6.0.1 on 2026-01-23 07:09

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0021_audititem'),
        ('governance', '0012_budgetpost_department_budgetpost_location'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DisposalRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('reason', models.CharField(max_length=50)),
                ('method', models.CharField(choices=[('Sale', 'Sale'), ('Junk', 'Junk/Scrap'), ('Donation', 'Donation'), ('Other', 'Other')], default='Junk', max_length=50)),
                ('condition_description', models.TextField()),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected'), ('Completed', 'Completed')], default='Pending', max_length=50)),
                ('approval_date', models.DateTimeField(blank=True, null=True)),
                ('disposal_proof', models.ImageField(blank=True, null=True, upload_to='disposal_proofs/')),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_disposals', to=settings.AUTH_USER_MODEL)),
                ('asset', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='assets.asset')),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disposal_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Disposal Request',
                'verbose_name_plural': 'Disposal Requests',
                'db_table': 'governance_disposalrequest',
            },
        ),
    ]
