# Generated by Django 6.0.1 on 2026-01-27 15:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('governance', '0013_disposalrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='budget',
            field=models.ForeignKey(blank=True, help_text='Funding Source', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projects', to='governance.budgetpost'),
        ),
    ]
