# Generated by Django 6.0.1 on 2026-01-27 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('governance', '0014_project_budget'),
    ]

    operations = [
        migrations.AddField(
            model_name='projecttask',
            name='weight',
            field=models.IntegerField(default=0),
        ),
    ]
