# Generated by Django 6.0.1 on 2026-01-27 16:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('governance', '0015_projecttask_weight'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projecttask',
            name='weight',
        ),
    ]
