# Generated by Django 6.0.1 on 2026-01-27 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('governance', '0016_remove_projecttask_weight'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='category',
            field=models.CharField(choices=[('Software Development', 'Software Development'), ('Infrastructure & Network', 'Infrastructure & Network'), ('Cybersecurity', 'Cybersecurity'), ('System Information / Data', 'System Information / Data'), ('Other', 'Other')], default='Software Development', max_length=50),
        ),
    ]
