# Generated by Django 6.0.1 on 2026-01-28 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('governance', '0017_project_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='projecttask',
            name='actual_hours',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='projecttask',
            name='completion_difficulty',
            field=models.CharField(blank=True, choices=[('Smooth', 'Smooth'), ('Minor Issues', 'Minor Issues'), ('Hard/Blocker', 'Hard/Blocker')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='projecttask',
            name='completion_note',
            field=models.TextField(blank=True, help_text='How was the task solved?'),
        ),
        migrations.AddField(
            model_name='projecttask',
            name='priority',
            field=models.CharField(choices=[('High', 'High'), ('Medium', 'Medium'), ('Low', 'Low')], default='Medium', max_length=20),
        ),
    ]
