# Generated by Django 6.0.1 on 2026-01-28 11:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0032_location_level_location_lft_location_rght_and_more'),
        ('governance', '0018_projecttask_actual_hours_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projects', to='assets.location'),
        ),
        migrations.AddField(
            model_name='project',
            name='vendor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projects', to='assets.vendor'),
        ),
    ]
