# Generated by Django 5.2.13 on 2026-10-02 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('governance', '0021_projectdocument'),
    ]

    operations = [
        migrations.AddField(
            model_name='projecttask',
            name='flag_reason',
            field=models.CharField(blank=True, help_text='Alasan kenapa task ditandai bermasalah', max_length=200),
        ),
        migrations.AddField(
            model_name='projecttask',
            name='is_flagged',
            field=models.BooleanField(default=False),
        ),
    ]
