# Generated by Django 5.2.13 on 2026-10-02 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('governance', '0022_add_task_flag_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectdocument',
            name='document_type',
            field=models.CharField(choices=[('Legal & Permit', 'Legal & Permit'), ('BAST & Handover', 'BAST & Handover'), ('Finance & Invoice', 'Finance & Invoice'), ('Design & Planning', 'Design & Planning'), ('Media & External Links', 'Media & External Links'), ('Other', 'Other')], default='Other', max_length=50),
        ),
        migrations.AddField(
            model_name='projectdocument',
            name='external_link',
            field=models.URLField(blank=True, help_text='Link to Google Drive, OneDrive, etc.', null=True),
        ),
        migrations.AddField(
            model_name='projectdocument',
            name='name',
            field=models.CharField(blank=True, help_text='Custom name or title', max_length=255),
        ),
        migrations.AlterField(
            model_name='projectdocument',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='project_documents/'),
        ),
    ]
