# Generated by Django 5.2.13 on 2026-10-07 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('governance', '0024_projectactivity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='category',
            field=models.CharField(choices=[('Software Development', 'Software Development'), ('Software Implementation', 'Software Implementation'), ('Infrastructure & Network', 'Infrastructure & Network'), ('Cybersecurity', 'Cybersecurity'), ('System Information / Data', 'System Information / Data'), ('Other', 'Other')], default='Software Development', max_length=50),
        ),
    ]
