# Generated by Django 5.2.13 on 2026-10-07 15:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('governance', '0025_alter_project_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailylogitem',
            name='project_task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='daily_log_items', to='governance.projecttask'),
        ),
        migrations.AlterField(
            model_name='dailylogitem',
            name='category',
            field=models.CharField(choices=[('Network', 'Network'), ('Server', 'Server'), ('Support', 'Support'), ('Development', 'Development'), ('Project / Implementation', 'Project / Implementation'), ('Meeting', 'Meeting'), ('Other', 'Other')], default='Other', max_length=50),
        ),
    ]
