# Generated by Django 5.2.13 on 2026-10-08 15:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('governance', '0027_project_on_hold_by_project_on_hold_date'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='projecttask',
            name='assigned_to',
            field=models.ForeignKey(blank=True, help_text='Legacy/Direct internal assignment', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='ProjectTeamMember',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('member_type', models.CharField(choices=[('Internal', 'Internal IT'), ('External', 'Vendor / External')], default='Internal', max_length=20)),
                ('external_name', models.CharField(blank=True, max_length=100)),
                ('role', models.CharField(max_length=100)),
                ('company', models.CharField(blank=True, help_text='Defaults to Internal IT or Vendor Name', max_length=100)),
                ('contact_info', models.CharField(blank=True, max_length=150)),
                ('internal_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='project_team_assignments', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_members', to='governance.project')),
            ],
        ),
        migrations.AddField(
            model_name='projecttask',
            name='team_member',
            field=models.ForeignKey(blank=True, help_text='Assign to specific project team member (Internal or Vendor)', null=True, on_delete=django.db.models.deletion.SET_NULL, to='governance.projectteammember'),
        ),
    ]
