# Generated by Django 5.2.13 on 2026-10-09 04:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('governance', '0029_project_rab_sheet_url_projectexpense'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectexpense',
            name='related_task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expenses', to='governance.projecttask'),
        ),
    ]
