# Generated by Django 5.2.13 on 2026-10-09 08:42

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('governance', '0031_projecttask_share_token_projectsubtask'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projecttask',
            name='share_token',
            field=models.UUIDField(blank=True, default=uuid.uuid4, editable=False, null=True, unique=True),
        ),
    ]
