# Generated by Django 6.0.1 on 2026-01-11 16:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assets', '0005_asset_infrastructure'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AssetMaintenance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('maintenance_code', models.CharField(editable=False, max_length=50, unique=True)),
                ('title', models.CharField(max_length=200)),
                ('scheduled_date', models.DateField()),
                ('completed_date', models.DateField(blank=True, null=True)),
                ('maintenance_type', models.CharField(choices=[('Preventive', 'Preventive'), ('Corrective', 'Corrective'), ('Upgrade', 'Upgrade')], max_length=20)),
                ('cost', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('status', models.CharField(choices=[('Scheduled', 'Scheduled'), ('In Progress', 'In Progress'), ('Completed', 'Completed'), ('Cancelled', 'Cancelled')], default='Scheduled', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('photo_before', models.ImageField(blank=True, upload_to='maintenance/before/')),
                ('photo_after', models.ImageField(blank=True, upload_to='maintenance/after/')),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maintenances', to='assets.asset')),
                ('technician', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_technician', to=settings.AUTH_USER_MODEL)),
                ('vendor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_vendor', to='assets.vendor')),
            ],
            options={
                'verbose_name': 'Asset Maintenance',
                'verbose_name_plural': 'Asset Maintenances',
            },
        ),
        migrations.CreateModel(
            name='InfraMaintenance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('maintenance_code', models.CharField(editable=False, max_length=50, unique=True)),
                ('title', models.CharField(max_length=200)),
                ('scheduled_date', models.DateField()),
                ('completed_date', models.DateField(blank=True, null=True)),
                ('maintenance_type', models.CharField(choices=[('Preventive', 'Preventive'), ('Corrective', 'Corrective'), ('Upgrade', 'Upgrade')], max_length=20)),
                ('cost', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('status', models.CharField(choices=[('Scheduled', 'Scheduled'), ('In Progress', 'In Progress'), ('Completed', 'Completed'), ('Cancelled', 'Cancelled')], default='Scheduled', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('photo_before', models.ImageField(blank=True, upload_to='maintenance/before/')),
                ('photo_after', models.ImageField(blank=True, upload_to='maintenance/after/')),
                ('infrastructure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maintenances', to='assets.infrastructure')),
                ('technician', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_technician', to=settings.AUTH_USER_MODEL)),
                ('vendor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_vendor', to='assets.vendor')),
            ],
            options={
                'verbose_name': 'Infrastructure Maintenance',
                'verbose_name_plural': 'Infrastructure Maintenances',
            },
        ),
    ]
