# Generated by Django 6.0.1 on 2026-01-24 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='assetmaintenance',
            name='maintenance_checklist',
            field=models.JSONField(blank=True, default=list, help_text="List of checklist items e.g. [{'task': 'Clean Fan', 'done': False}]"),
        ),
        migrations.AddField(
            model_name='inframaintenance',
            name='maintenance_checklist',
            field=models.JSONField(blank=True, default=list, help_text="List of checklist items e.g. [{'task': 'Clean Fan', 'done': False}]"),
        ),
    ]
