# Generated by Django 5.2.13 on 2026-09-30 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0004_add_priority_and_parent_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='assetmaintenance',
            name='actual_completion_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='assetmaintenance',
            name='actual_start_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='assetmaintenance',
            name='downtime_duration',
            field=models.DurationField(blank=True, help_text='Duration of asset downtime', null=True),
        ),
        migrations.AddField(
            model_name='assetmaintenance',
            name='invoice_number',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='assetmaintenance',
            name='labor_cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='assetmaintenance',
            name='parts_cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='assetmaintenance',
            name='resolution_notes',
            field=models.TextField(blank=True, help_text='Detailed steps taken to resolve the issue'),
        ),
        migrations.AddField(
            model_name='assetmaintenance',
            name='root_cause',
            field=models.TextField(blank=True, help_text='Root cause of the problem (for Corrective)'),
        ),
        migrations.AddField(
            model_name='assetmaintenance',
            name='vendor_contact',
            field=models.CharField(blank=True, help_text="Name of the vendor's technician/contact", max_length=100),
        ),
        migrations.AddField(
            model_name='assetmaintenance',
            name='warranty_expiry_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='inframaintenance',
            name='actual_completion_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='inframaintenance',
            name='actual_start_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='inframaintenance',
            name='downtime_duration',
            field=models.DurationField(blank=True, help_text='Duration of asset downtime', null=True),
        ),
        migrations.AddField(
            model_name='inframaintenance',
            name='invoice_number',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='inframaintenance',
            name='labor_cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='inframaintenance',
            name='parts_cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='inframaintenance',
            name='resolution_notes',
            field=models.TextField(blank=True, help_text='Detailed steps taken to resolve the issue'),
        ),
        migrations.AddField(
            model_name='inframaintenance',
            name='root_cause',
            field=models.TextField(blank=True, help_text='Root cause of the problem (for Corrective)'),
        ),
        migrations.AddField(
            model_name='inframaintenance',
            name='vendor_contact',
            field=models.CharField(blank=True, help_text="Name of the vendor's technician/contact", max_length=100),
        ),
        migrations.AddField(
            model_name='inframaintenance',
            name='warranty_expiry_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
