# Generated by Django 5.2.13 on 2026-10-08 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0005_assetmaintenance_actual_completion_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maintenanceschedule',
            name='frequency',
            field=models.CharField(choices=[('Weekly', 'Weekly'), ('Monthly', 'Monthly'), ('Quarterly', 'Quarterly'), ('Semi-Annually', 'Semi-Annually (6 Months)'), ('Yearly', 'Yearly')], default='Monthly', max_length=20),
        ),
    ]
