# Generated by Django 6.0.1 on 2026-01-22 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TelegramConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bot_token', models.CharField(help_text='Telegram Bot Token', max_length=255)),
                ('chat_id', models.CharField(help_text='Default Chat ID / Group ID', max_length=100)),
                ('is_active', models.BooleanField(default=True, verbose_name='Enable Telegram Notifications')),
            ],
            options={
                'verbose_name': 'Telegram Configuration',
                'verbose_name_plural': 'Telegram Configuration',
            },
        ),
        migrations.CreateModel(
            name='WhatsAppConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_url', models.CharField(default='https://api.fonnte.com/send', help_text='API Endpoint URL (e.g. Fonnte, Twilio)', max_length=255)),
                ('api_token', models.CharField(help_text='API Authorization Token', max_length=255)),
                ('default_target_number', models.CharField(blank=True, help_text='Default number for admin alerts (e.g. 62812xxxx)', max_length=50, null=True)),
                ('is_active', models.BooleanField(default=True, verbose_name='Enable WhatsApp Notifications')),
            ],
            options={
                'verbose_name': 'WhatsApp Configuration',
                'verbose_name_plural': 'WhatsApp Configuration',
            },
        ),
    ]
