# Generated by Django 6.0.1 on 2026-01-22 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('smtp_host', models.CharField(help_text='SMTP Server Host (e.g. smtp.gmail.com)', max_length=255)),
                ('smtp_port', models.IntegerField(default=587, help_text='SMTP Port (e.g. 587)')),
                ('smtp_user', models.CharField(help_text='SMTP User / Email Address', max_length=255)),
                ('smtp_password', models.CharField(help_text='SMTP Password / App Password', max_length=255)),
                ('use_tls', models.BooleanField(default=True, verbose_name='Use TLS')),
                ('default_from_email', models.CharField(default='noreply@example.com', help_text="Default 'From' Email Address", max_length=255)),
                ('is_active', models.BooleanField(default=True, verbose_name='Enable Email Notifications')),
            ],
            options={
                'verbose_name': 'Email Configuration (SMTP)',
                'verbose_name_plural': 'Email Configuration (SMTP)',
            },
        ),
    ]
