# Generated by Django 6.0.1 on 2026-01-12 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0003_ticket_due_date_ticket_feedback_ticket_rating_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='title',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
