# Generated by Django 6.0.1 on 2026-01-12 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TelegramConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bot_token', models.CharField(help_text='API Token from BotFather', max_length=200)),
                ('alert_chat_id', models.CharField(help_text='Target Chat ID (e.g., -100xxxx)', max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('description', models.CharField(default='IT Team Group', max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Telegram Configuration',
                'verbose_name_plural': 'Telegram Configuration',
            },
        ),
    ]
