# Generated by Django 6.0.1 on 2026-01-22 15:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_notification'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TelegramConfig',
        ),
    ]
